apiVersion: v2
name: joplin
description: A Helm chart for deploying Joplin Server
type: application
version: 0.1.0           # chart version
appVersion: "latest"     # Joplin Server image tag
maintainers:
  - name: Tobias Sackmann
    email: tobas.gerhard.sackmann@gmail.com
sources:
  - https://github.com/laurent22/joplin
home: https://joplinapp.org
keywords:
  - notes
  - markdown
  - self-hosted
  - joplin
icon: https://joplinapp.org/images/Icon512.png
dependencies:
  - name: postgresql
    version: 15.5.14   # check for the latest version on ArtifactHub
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
