apiVersion: v1
kind: Service
metadata:
  name: {{ include "joplin.fullname" . }}
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22300
  selector:
    app.kubernetes.io/name: {{ include "joplin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
